steps:
# install dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ["ci"]
# build the site
- name: 'gcr.io/cloud-builders/npm'
  args: ["run", "build"]
# export the site
- name: 'gcr.io/cloud-builders/npm'
  args: ["run", "export"]

# setup netlify-cli to deploy
- name: 'gcr.io/cloud-builders/npm'
  args: ['install', "netlify-cli"]